# hand-written specials, one program per entry
PRE = <<~'RB'
  def nilf
    puts "nilf"
    nil
  end
  $c = 0
  def bump
    $c += 1
    puts "bump"
    nil
  end
  class K
    def initialize(n = "k")
      @name = n
    end
    def name = @name
    def v=(x)
      @v = x
      42
    end
    def v = @v
    def w=(x)
      @w = x
      "wret"
    end
    def w = @w
  end
RB
H = {}
H["clsbody_const"] = "class K\n  O = K.new\n  Z = (O.v = nilf)\n  p Z\n  p O.v\nend\np K::Z\n"
H["clsbody_p"] = "class K\n  O = K.new\n  p(O.v = nilf)\n  p O.v\nend\n"
H["clsbody_stmt"] = "class K\n  O = K.new\n  O.v = nilf\n  p O.v\nend\n"
H["clsbody_ivar"] = "class K\n  @ci = (K.new.v = nilf)\n  def self.ci = @ci\nend\np K.ci\n"
H["clsbody_cvar"] = "class K\n  @@cv = (K.new.v = nilf)\n  def self.cv = @@cv\nend\np K.cv\n"
H["modbody"] = "module M\n  A = K.new\n  p(A.v = nilf)\n  y = (A.v = nilf)\n  p y\nend\n"
H["dflt_self"] = "class K\n  def dflt(q = (self.v = nilf))\n    q\n  end\nend\nk = K.new\np k.dflt\np k.v\np k.dflt(3)\n"
H["dflt_other"] = "def df(o, q = (o.v = nilf))\n  q\nend\nk = K.new\np df(k)\np k.v\np df(k, 4)\n"
H["dflt_kw"] = "def kw(o, q: (o.v = nilf))\n  q\nend\nk = K.new\np kw(k)\np k.v\n"
H["dflt_lam"] = "l = ->(o, q = (o.v = nilf)) { q }\nk = K.new\np l.call(k)\np k.v\n"
H["smeth"] = "class K\n  def self.mk\n    k = K.new\n    k.v = nilf\n  end\nend\np K.mk\n"
H["gvar_init"] = "$g = K.new\n$h = ($g.v = nilf)\np $h\np $g.v\n"
H["then"] = "k = K.new\np(k.then { |o| o.v = nilf })\np k.v\n"
H["map"] = "ks = [K.new, K.new]\nx = ks.map { |o| o.v = nilf }\np x\np ks[0].v\n"
H["at_exit"] = "$g = K.new\nat_exit { $g.v = nilf; p $g.v }\nputs \"main\"\n"
H["begin_blk"] = "BEGIN { puts \"begin\" }\nk = K.new\nk.v = nilf\np k.v\n"
H["end_blk"] = "$k = K.new\nEND { $k.v = nilf; p $k.v }\nputs \"main\"\n"
H["init"] = "class H\n  def initialize(o)\n    @r = (o.v = nilf)\n  end\n  def r = @r\nend\nk = K.new\np H.new(k).r\np k.v\n"
H["init_self"] = "class H2\n  def initialize\n    self.z = nilf\n    @q = (self.z = bump)\n  end\n  def z=(x)\n    @z = x\n    7\n  end\n  def z = @z\n  def q = @q\nend\nh = H2.new\np h.z\np h.q\n"
H["attrinit"] = "class H3\n  attr_reader :z\n  def z=(x)\n    @z = x\n  end\n  def initialize\n    @z = 5\n  end\nend\nh = H3.new\np h.z\nh.z = nilf\np h.z\nh.z = 6\np h.z\n"
H["struct_w"] = "S = Struct.new(:a, :b) do\n  def w=(x)\n    self.a = x\n    9\n  end\nend\ns = S.new(1, 2)\np(s.w = nilf)\np s.a\ns.a = nilf\np s.a\np(s.b = nilf)\np s.b\n"
H["struct_kw"] = "S = Struct.new(:a, keyword_init: true) do\n  def w=(x)\n    self.a = x\n  end\nend\ns = S.new(a: 1)\ns.w = nilf\np s.a\n"
H["sing_obj"] = "k = K.new\ndef k.z=(x)\n  @z = x\n  5\nend\ndef k.z = @z\np(k.z = nilf)\np k.z\n"
H["sing_cls"] = "class K\n  def self.cv=(x)\n    @cv = x\n    5\n  end\n  def self.cv = @cv\nend\np(K.cv = nilf)\np K.cv\nK.cv = bump\np K.cv\n"
H["sing_cls2"] = "class K\n  class << self\n    def cv=(x)\n      @cv = x\n      5\n    end\n    def cv = @cv\n  end\nend\ny = (K.cv = nilf)\np y\np K.cv\n"
H["mod_fn"] = "module Cfg\n  def self.lvl=(x)\n    @lvl = x\n    1\n  end\n  def self.lvl = @lvl\nend\np(Cfg.lvl = nilf)\np Cfg.lvl\nCfg.lvl = 3\np Cfg.lvl\ny = (Cfg.lvl = bump)\np y\n"
H["chain2"] = "a = K.new\nb = K.new\na.v = b.v = nilf\np a.v\np b.v\n"
H["chain2w"] = "a = K.new\nb = K.new\nz = (a.v = b.w = nilf)\np z\np a.v\np b.w\n"
H["chain3"] = "a = K.new\nb = K.new\nc = K.new\na.v = b.w = c.v = nilf\np a.v\np b.w\np c.v\n"
H["chain_lit"] = "a = K.new\nb = K.new\na.v = b.w = nil\np a.v\np b.w\np(a.v = b.w = nil)\n"
H["chain_mixed"] = "a = K.new\nb = K.new\nx = a.v = b.w = nilf\np x\n"
H["nest_seq"] = "a = K.new\nb = K.new\na.v = (b.w = 5; nil)\np a.v\np b.w\n"
H["nest_seq2"] = "a = K.new\nb = K.new\np(a.v = (bump; b.w = nil))\np a.v\np b.w\n"
H["nest_seq3"] = "a = K.new\nb = K.new\np(a.v = (b.w = nilf; bump))\np a.v\np b.w\n"
H["nest_if"] = "a = K.new\nb = K.new\np(a.v = (b.w = nilf if $c < 9))\np a.v\np b.w\n"
H["nest_or"] = "a = K.new\nb = K.new\np(a.v = ((b.w = nilf) || (b.v = bump)))\np a.v\np b.w\np b.v\n"
H["nest_arg"] = "def idn(x)\n  puts \"idn\"\n  nil\nend\na = K.new\nb = K.new\np(a.v = idn(b.w = nilf))\np a.v\np b.w\n"
H["nest_arg2"] = "def idn(x)\n  p x\n  nil\nend\na = K.new\nb = K.new\np(a.v = idn(b.w = 5))\np a.v\np b.w\n"
H["nest_arg3"] = "def idn(x)\n  p x\n  nil\nend\na = K.new\nb = K.new\np(a.v = idn(b.w = \"s\"))\np a.v\np b.w\n"
H["nest_arg4"] = "def idn(x)\n  p x\n  nil\nend\na = K.new\nb = K.new\na.v = idn(b.w = (bump; 6))\np a.v\np b.w\n"
H["nest_arg5"] = "def idn(x)\n  p x\n  nil\nend\na = K.new\nb = K.new\na.v = idn((b.w = (bump; 6)) + 1)\np a.v\np b.w\n"
H["nest_interp"] = "def say(s)\n  puts s\n  nil\nend\na = K.new\nb = K.new\na.v = say(\"got \#{b.w = (bump; 6)}\")\np a.v\np b.w\n"
H["nest_interp2"] = "def say(s)\n  puts s\n  nil\nend\na = K.new\nb = K.new\na.v = say(\"got \#{(b.w = (bump; \"q\"))}\")\np a.v\np b.w\n"
H["nest_blk"] = "def yb\n  p yield\n  nil\nend\na = K.new\nb = K.new\na.v = yb { b.w = (bump; 6) }\np a.v\np b.w\n"
H["nest_blk2"] = "def yb\n  p yield\n  nil\nend\na = K.new\nb = K.new\na.v = yb { b.w = nilf }\np a.v\np b.w\n"
H["nest_blk3"] = "a = K.new\nb = K.new\na.v = [1, 2].each { |i| p(b.w = (bump; i)) }.clear.first\np a.v\np b.w\n"
H["nest_puts"] = "a = K.new\nb = K.new\na.v = puts(b.w = (bump; 6))\np a.v\np b.w\n"
H["nest_p"] = "a = K.new\nb = K.new\na.v = (p(b.w = (bump; 6)); nil)\np a.v\np b.w\n"
H["nest_puts_s"] = "a = K.new\nb = K.new\na.v = puts(b.w = (bump; \"str\"))\np a.v\np b.w\n"
H["nest_asgn"] = "a = K.new\nb = K.new\na.v = (t = (b.w = (bump; 6)); p t; nil)\np a.v\np b.w\n"
H["nest_cond"] = "a = K.new\nb = K.new\na.v = (if (b.w = (bump; 6)) then nilf else bump end)\np a.v\np b.w\n"
H["nest_cond2"] = "a = K.new\nb = K.new\na.v = (if (b.w = nilf) then nilf else bump end)\np a.v\np b.w\n"
H["nest_self"] = "a = K.new\na.v = (a.w = (bump; 6); nil)\np a.v\np a.w\na.v = (p(a.w = (bump; 8)); nil)\n"
H["nest_writer_calls"] = "class K\n  def both=(x)\n    self.v = x\n    self.w = (bump; x)\n    @r = (self.v = nilf)\n    :b\n  end\n  def r = @r\nend\na = K.new\np(a.both = nilf)\np a.v\np a.w\np a.r\n"
H["writer_in_writer"] = "class K\n  def z=(x)\n    r = (self.v = x)\n    p r\n    @z = r\n  end\n  def z = @z\nend\na = K.new\np(a.z = nilf)\np a.z\np a.v\n"
H["multi_asgn"] = "a = K.new\na.v, a.w = nilf, bump\np a.v\np a.w\n"
H["multi_asgn2"] = "a = K.new\nx, a.v = 1, nilf\np x\np a.v\n"
H["multi_splat"] = "def two\n  puts \"two\"\n  [nil, nil]\nend\na = K.new\na.v, a.w = two\np a.v\np a.w\n"
H["orw"] = "a = K.new\na.v ||= nilf\np a.v\na.v ||= 5\np a.v\na.v ||= nilf\np a.v\n"
H["andw"] = "a = K.new\na.v = 5\na.v &&= nilf\np a.v\na.v &&= nilf\np a.v\n"
H["opw"] = "class C2\n  def n=(x)\n    @n = x\n  end\n  def n = @n\nend\na = C2.new\na.n = 1\na.n += 2\np a.n\na.n = nilf\np a.n\n"
H["safe_nil_lit"] = "a = nil\na&.v = nilf\np a\n"
H["safe_nil_m"] = "def none = nil\nnone&.v = nilf\nputs \"ok\"\n"
H["safe_val"] = "a = K.new\nb = $c > 5 ? a : nil\np(b&.v = nilf)\np(a&.v = nilf)\np a.v\n"
H["safe_chain"] = "class H\n  def initialize(o)\n    @o = o\n  end\n  def o = @o\nend\nh = H.new(K.new)\nh2 = H.new(nil)\np(h.o&.v = nilf)\np(h2.o&.v = nilf)\np h.o.v\n"
H["recv_eff_order"] = "def get(o)\n  puts \"get\"\n  o\nend\na = K.new\np(get(a).v = nilf)\nget(a).v = (bump; nil)\np a.v\n"
H["recv_new_eff"] = "class N\n  def initialize\n    puts \"new\"\n  end\n  def v=(x)\n    puts \"set \#{x.inspect}\"\n  end\nend\nN.new.v = nilf\np(N.new.v = nilf)\n"
H["recv_idx_eff"] = "def ix\n  puts \"ix\"\n  0\nend\narr = [K.new]\narr[ix].v = nilf\np arr[0].v\np(arr[ix].v = bump)\n"
H["recv_writer_arg_eff"] = "def get(o)\n  puts \"get\"\n  o\nend\ndef nila(o)\n  puts \"nila\"\n  nil\nend\na = K.new\nget(a).v = nila(get(a))\np a.v\n"
H["yield_val"] = "def run(o)\n  o.v = yield\nend\na = K.new\np run(a) { nil }\np a.v\np run(a) { bump }\n"
H["yield_val2"] = "def run(o)\n  r = (o.v = yield)\n  p r\n  o.v\nend\na = K.new\np run(a) { nilf }\n"
H["blk_call"] = "def run(o, &b)\n  o.v = b.call\nend\na = K.new\np run(a) { nilf }\np a.v\n"
H["proc_call"] = "a = K.new\npr = proc { nilf }\np(a.v = pr.call)\np a.v\nl = -> { bump }\np(a.v = l.())\n"
H["meth_obj"] = "a = K.new\nm = method(:nilf)\np(a.v = m.call)\np a.v\n"
H["send"] = "a = K.new\np(a.v = send(:nilf))\np a.v\np a.send(:v=, nilf)\np a.public_send(:v=, bump)\n"
H["send_setter"] = "a = K.new\np a.send(:v=, nilf)\np a.v\n"
H["send_w"] = "a = K.new\nr = a.send(:w=, nilf)\np r\np a.w\n"
H["attr_beside"] = "class A2\n  attr_writer :x\n  attr_reader :x, :y\n  def y=(q)\n    self.x = q\n    @y = q\n  end\nend\na = A2.new\np(a.y = nilf)\np a.x\np a.y\np(a.x = nilf)\n"
H["attr_acc_over"] = "class A3\n  attr_accessor :x\n  def x=(q)\n    puts \"over\"\n    @x = q\n  end\nend\na = A3.new\np(a.x = nilf)\np a.x\na.x = 5\np a.x\n"
H["sub_over"] = "class B1\n  def x=(q)\n    @x = q\n    1\n  end\n  def x = @x\nend\nclass B2 < B1\n  def x=(q)\n    puts \"B2\"\n    @x = q\n    2\n  end\nend\ndef pick(f) = f ? B2.new : B1.new\no = pick(true)\np(o.x = nilf)\np o.x\no2 = pick(false)\np(o2.x = nilf)\n[B1.new, B2.new].each { |z| p(z.x = nilf) }\n"
H["sub_over_super"] = "class B1\n  def x=(q)\n    @x = q\n    1\n  end\n  def x = @x\nend\nclass B2 < B1\n  def x=(q)\n    super(q)\n    p(super)\n    2\n  end\nend\no = B2.new\np(o.x = nilf)\np o.x\n"
H["super_nilval"] = "class B1\n  def x=(q)\n    @x = q\n    1\n  end\n  def x = @x\nend\nclass B2 < B1\n  def x=(q)\n    super(nilf)\n  end\nend\no = B2.new\np(o.x = 5)\np o.x\n"
H["int_param"] = "class C2\n  def n=(x)\n    @n = x.to_i\n  end\n  def n = @n\nend\na = C2.new\na.n = 5\np a.n\na.n = \"7\"\np a.n\np(a.n = nilf)\np a.n\n"
H["int_param_plus"] = "class C2\n  def n=(x)\n    @n = x + 1\n  end\n  def n = @n\nend\na = C2.new\na.n = 5\np a.n\na.n = nilf\np a.n\n"
H["int_param_plus_only"] = "class C2\n  def n=(x)\n    @n = x + 1\n  end\n  def n = @n\nend\na = C2.new\na.n = nilf\np a.n\n"
H["int_param_mul"] = "class C2\n  def n=(x)\n    @n = x * 2\n  end\n  def n = @n\nend\na = C2.new\na.n = 5\np a.n\na.n = (bump; nil)\np a.n\n"
H["int_param_cmp"] = "class C2\n  def n=(x)\n    @n = x > 3\n  end\n  def n = @n\nend\na = C2.new\na.n = 5\np a.n\na.n = nilf\np a.n\n"
H["str_param_len"] = "class C2\n  def n=(x)\n    @n = x.length\n  end\n  def n = @n\nend\na = C2.new\na.n = \"abc\"\np a.n\na.n = nilf\np a.n\n"
H["str_param_cat"] = "class C2\n  def n=(x)\n    @n = \"<\" + x + \">\"\n  end\n  def n = @n\nend\na = C2.new\na.n = \"abc\"\np a.n\na.n = nilf\np a.n\n"
H["str_param_interp"] = "class C2\n  def n=(x)\n    @n = \"<\#{x}>\"\n  end\n  def n = @n\nend\na = C2.new\na.n = \"abc\"\np a.n\na.n = nilf\np a.n\n"
H["obj_param_call"] = "class C2\n  def n=(x)\n    @n = x.name\n  end\n  def n = @n\nend\na = C2.new\na.n = K.new(\"kk\")\np a.n\na.n = nilf\np a.n\n"
H["flt_param"] = "class C2\n  def n=(x)\n    @n = x * 1.5\n  end\n  def n = @n\nend\na = C2.new\na.n = 2.0\np a.n\na.n = nilf\np a.n\n"
H["arr_param"] = "class C2\n  def n=(x)\n    @n = x.size\n  end\n  def n = @n\nend\na = C2.new\na.n = [1, 2]\np a.n\na.n = nilf\np a.n\n"
H["slot_int_read"] = "class C2\n  def n=(x)\n    @n = x\n  end\n  def n = @n\n  def twice = @n * 2\nend\na = C2.new\na.n = 5\np a.twice\na.n = nilf\np a.n\np a.n.nil?\np a.twice\n"
H["slot_str_read"] = "class C2\n  def n=(x)\n    @n = x\n  end\n  def n = @n\n  def len = @n.length\nend\na = C2.new\na.n = \"abc\"\np a.len\na.n = nilf\np a.n\np a.n.nil?\np a.len\n"
H["slot_flt_read"] = "class C2\n  def n=(x)\n    @n = x\n  end\n  def n = @n\nend\na = C2.new\na.n = 2.5\np a.n\na.n = nilf\np a.n\np a.n.nil?\np(a.n ? 1 : 2)\n"
H["slot_obj_read"] = "class C2\n  def n=(x)\n    @n = x\n  end\n  def n = @n\nend\na = C2.new\na.n = K.new(\"kk\")\np a.n.name\na.n = nilf\np a.n.nil?\np a.n&.name\np a.n.name\n"
H["slot_bool_read"] = "class C2\n  def n=(x)\n    @n = x\n  end\n  def n = @n\nend\na = C2.new\na.n = true\np a.n\na.n = nilf\np a.n\np a.n.nil?\na.n = false\np a.n\n"
H["slot_sym_read"] = "class C2\n  def n=(x)\n    @n = x\n  end\n  def n = @n\nend\na = C2.new\na.n = :s\np a.n\na.n = nilf\np a.n\np a.n.nil?\n"
H["slot_int_val"] = "class C2\n  def n=(x)\n    @n = x\n  end\n  def n = @n\nend\na = C2.new\na.n = 5\ny = (a.n = nilf)\np y\nz = (a.n = 6)\np z\np [a.n = nilf, a.n = 7]\n"
H["loop_fresh"] = "$keep = []\ndef nal(i)\n  $keep << (\"x\" * (i + 20))\n  nil\nend\nt = 0\ni = 0\nwhile i < 200\n  k = K.new(\"f\#{i}\")\n  r = (k.v = nal(i))\n  t += 1 if r.nil? && k.v.nil?\n  i += 1\nend\np t\np $keep.size\n"
H["loop_fresh_recv"] = "$keep = []\ndef nal(i)\n  $keep << (\"x\" * (i + 20))\n  nil\nend\nt = 0\n200.times do |i|\n  K.new(\"f\#{i}\").v = nal(i)\n  t += 1 if (K.new(\"g\#{i}\").w = nal(i)).nil?\nend\np t\np $keep.size\n"
H["loop_fresh_arg"] = "def nal(o)\n  s = o.name + \"!\"\n  $last = s\n  nil\nend\nt = 0\n200.times do |i|\n  k = K.new(\"f\#{i}\")\n  k.v = nal(K.new(\"tmp\#{i}\"))\n  t += $last.length\nend\np t\n"
H["raise_writer"] = "class R\n  def v=(x)\n    raise ArgumentError, \"nope\" if x.nil?\n    @v = x\n  end\nend\nr = R.new\nbegin\n  r.v = nilf\nrescue ArgumentError => e\n  puts \"rescued \#{e.message}\"\nend\nr.v = nilf\nputs \"unreached\"\n"
H["raise_value"] = "def boom\n  raise \"boom\"\n  nil\nend\na = K.new\nbegin\n  a.v = boom\nrescue => e\n  puts e.message\nend\np a.v\na.v = boom\n"
H["raise_value2"] = "def boom(f)\n  raise IOError, \"io\" if f\n  nil\nend\na = K.new\na.v = 3\nx = begin\n  (a.v = boom(true))\nrescue IOError\n  :io\nend\np x\np a.v\np(a.v = boom(false))\n"
H["retry_ens"] = "a = K.new\nn = 0\nbegin\n  n += 1\n  a.v = (raise \"x\" if n < 2; bump)\nrescue\n  retry\nensure\n  puts \"ens\"\nend\np n\np a.v\n"
H["throw_val"] = "def th\n  throw :t, 5\n  nil\nend\na = K.new\na.v = 1\nr = catch(:t) { a.v = th }\np r\np a.v\n"
H["break_val"] = "a = K.new\nr = [1, 2].each { |i| a.v = (break 9 if i > 0; nil) }\np r\n"
H["next_val"] = "a = K.new\nr = [1, 2].map { |i| a.v = (next 7 if i > 1; nilf) }\np r\n"
H["ret_val"] = "def rr(o, f)\n  o.v = (return 5 if f; nilf)\nend\na = K.new\np rr(a, false)\np rr(a, true)\n"
H["frozen"] = "a = K.new\na.freeze\nbegin\n  a.v = nilf\nrescue => e\n  puts e.class\nend\n"
H["respond"] = "a = K.new\np a.respond_to?(:v=)\np(a.v = nilf)\n"
H["defmeth"] = "class D\n  define_method(:v=) { |x| @v = x; 3 }\n  define_method(:v) { @v }\nend\nd = D.new\np(d.v = nilf)\np d.v\n"
H["mmiss"] = "class MM\n  def method_missing(n, *a)\n    puts \"mm \#{n}\"\n    nil\n  end\n  def respond_to_missing?(*) = true\nend\nm = MM.new\np(m.zz = nilf)\n"
H["index_set"] = "class IX\n  def []=(k, x)\n    puts \"set \#{k} \#{x.inspect}\"\n    5\n  end\nend\ni = IX.new\np(i[1] = nilf)\ni[2] = bump\n"
H["underscore"] = "class U\n  def _v=(x)\n    @v = x\n    1\n  end\n  def V=(x)\n    @v = x\n    2\n  end\n  def v = @v\nend\nu = U.new\np(u._v = nilf)\np(u.V = bump)\np u.v\n"
H["op_methods"] = "class U\n  def ==(x)\n    puts \"eq\"\n    true\n  end\n  def <=(x)\n    puts \"le\"\n    true\n  end\nend\nu = U.new\np(u == nilf)\np(u <= bump)\n"
H["predicate_q"] = "class U\n  def ok!(x)\n    puts \"ok\"\n    x\n  end\nend\nu = U.new\np u.ok!(nilf)\n"
H["two_classes"] = "class A1\n  def v=(x)\n    @v = x\n    :a\n  end\n  def v = @v\nend\nclass A2\n  def v=(x)\n    @v = x.to_s\n    :b\n  end\n  def v = @v\nend\n[A1.new, A2.new].each { |o| p(o.v = nilf); p o.v }\na = A1.new\nb = A2.new\np(a.v = nilf)\np(b.v = bump)\np b.v\n"
H["void_writer"] = "class VW\n  def v=(x)\n    puts \"vw \#{x.inspect}\"\n  end\nend\no = VW.new\np(o.v = nilf)\ny = (o.v = bump)\np y\n"
H["writer_ret_self"] = "class VW\n  def v=(x)\n    @v = x\n    self\n  end\n  def v = @v\nend\no = VW.new\np((o.v = nilf).nil?)\ny = (o.v = bump)\np y\n"
H["writer_ret_nil"] = "class VW\n  def v=(x)\n    @v = 1\n    nil\n  end\n  def v = @v\nend\no = VW.new\np(o.v = nilf)\np o.v\n"
H["writer_only_nilcalls"] = "class VW\n  def v=(x)\n    @v = x\n  end\n  def v = @v\nend\no = VW.new\no.v = nilf\np o.v\np o.v.nil?\np o.v.inspect\np [o.v]\n"
H["writer_nil_then_str"] = "class VW\n  def v=(x)\n    @v = x\n  end\n  def v = @v\nend\no = VW.new\no.v = nilf\np o.v\no.v = \"abc\"\np o.v\np o.v.length\no.v = bump\np o.v\n"
H["writer_str_append"] = "class VW\n  def v=(x)\n    @v = x\n  end\n  def v = @v\nend\no = VW.new\ns = +\"ab\"\no.v = s\ns << \"c\"\np o.v\no.v = nilf\np o.v\np s\n"
H["writer_stores_param_twice"] = "class VW\n  def v=(x)\n    @a = x\n    @b = x\n    p [x, x]\n  end\n  def a = @a\n  def b = @b\nend\no = VW.new\no.v = nilf\np o.a\np o.b\n"
H["param_reassign"] = "class VW\n  def v=(x)\n    x = 5 if x.nil?\n    @v = x\n  end\n  def v = @v\nend\no = VW.new\np(o.v = nilf)\np o.v\n"
H["param_or"] = "class VW\n  def v=(x)\n    @v = x || \"dflt\"\n  end\n  def v = @v\nend\no = VW.new\np(o.v = nilf)\np o.v\no.v = \"given\"\np o.v\n"
H["param_case"] = "class VW\n  def v=(x)\n    @v = case x\n         when nil then :nil\n         when Integer then :int\n         else :other\n         end\n  end\n  def v = @v\nend\no = VW.new\no.v = nilf\np o.v\no.v = 3\np o.v\n"
H["param_isa"] = "class VW\n  def v=(x)\n    @v = x.is_a?(NilClass)\n    @k = x.class\n  end\n  def v = @v\n  def k = @k\nend\no = VW.new\no.v = nilf\np o.v\np o.k\n"
H["cond_expr_stmt"] = "a = K.new\na.v = nilf if true\na.v = bump unless false\n(a.v = nilf) while false\nx = 0\nx += 1 until (a.v = bump).nil?\np x\n"
H["in_args_mid"] = "def three(a, b, c)\n  p [a, b, c]\nend\nk = K.new\nthree((puts \"1\"; 1), (k.v = nilf), (puts \"3\"; 3))\n"
H["in_arr_mid"] = "k = K.new\np [(puts \"1\"; 1), (k.v = nilf), (puts \"3\"; 3)]\n"
H["in_hash_val"] = "k = K.new\nh = {a: (puts \"1\"; 1), b: (k.v = nilf), c: (puts \"3\"; 3)}\np h[:a]\np h[:b]\np h.size\n"
H["in_str"] = "k = K.new\ns = \"a\#{k.v = nilf}b\#{k.w = bump}c\"\np s\np s.length\n"
H["in_cmp"] = "k = K.new\np((k.v = nilf) == (k.w = bump))\np((k.v = nilf).equal?(nil))\np((k.v = nilf) != nil)\n"
H["in_ret"] = "def f1(k)\n  return k.v = nilf\nend\ndef f2(k)\n  k.v = nilf\nend\ndef f3(k) = (k.w = bump)\nk = K.new\np f1(k)\np f2(k)\np f3(k)\nx = f2(k)\np x.nil?\n"
H["in_ret_typed"] = "def f4(k, f)\n  return 5 if f\n  k.v = nilf\nend\nk = K.new\np f4(k, true)\np f4(k, false)\np f4(k, false).nil?\n"
H["in_ret_str"] = "def f5(k, f)\n  return \"s\" if f\n  k.v = nilf\nend\nk = K.new\np f5(k, true)\np f5(k, false)\n"
H["in_local_typed"] = "k = K.new\nx = 5\nx = (k.v = nilf) if $c == 0\np x\nx = 6\np x + 1\ny = \"s\"\ny = (k.v = bump)\np y\n"
H["in_ivar_typed"] = "class HH\n  def initialize(k)\n    @n = 5\n    @n = (k.v = nilf)\n  end\n  def n = @n\nend\np HH.new(K.new).n\n"
H["in_arr_push"] = "k = K.new\narr = [1, 2]\narr << (k.v = nilf)\np arr\narr.push(k.w = bump)\np arr\n"
H["in_hash_store"] = "k = K.new\nh = {}\nh[:a] = (k.v = nilf)\np h[:a]\np h.key?(:a)\n"
H["in_and_or"] = "k = K.new\np((k.v = nilf) || (k.w = bump) || 3)\np((k.v = nilf) && 3)\np(true && (k.v = nilf))\np(false || (k.v = nilf))\nz = (k.v = nilf) ? :t : :f\np z\n"
H["unless_not"] = "k = K.new\nputs \"a\" unless (k.v = nilf)\nputs \"b\" if !(k.v = nilf)\nputs \"c\" if (k.v = nilf).nil?\nputs((k.v = nilf).to_s.empty?)\n"
H["to_s_methods"] = "k = K.new\np((k.v = nilf).to_s)\np((k.v = nilf).to_a)\np((k.v = nilf).inspect)\np((k.v = nilf).to_i)\np((k.v = nilf).to_h.size)\np((k.v = nilf).class)\np((k.v = nilf) & true)\np((k.v = nilf) | true)\n"
H["as_recv_safe"] = "k = K.new\np((k.v = nilf)&.length)\np((k.v = nilf)&.name)\n"
H["as_recv_user"] = "class NilClass\n  def hello = \"hi\"\nend\nk = K.new\np((k.v = nilf).hello)\n"
H["as_recv_nomethod"] = "k = K.new\np((k.v = nilf).length)\n"
H["as_recv_nomethod2"] = "k = K.new\nx = (k.v = nilf)\np x.name\n"
H["as_op_plus"] = "k = K.new\np((k.v = nilf) + 1)\n"
H["as_arg_typed"] = "def dbl(n)\n  n * 2\nend\nk = K.new\np dbl(4)\np dbl(k.v = nilf)\n"
H["as_arg_str"] = "def ln(s)\n  s.length\nend\nk = K.new\np ln(\"abc\")\np ln(k.v = nilf)\n"
H["as_arg_nilok"] = "def sh(s)\n  s.nil? ? \"nil!\" : s\nend\nk = K.new\np sh(\"abc\")\np sh(k.v = nilf)\n"
H["as_arg_obj"] = "def nm(o)\n  o.nil? ? \"none\" : o.name\nend\nk = K.new(\"kk\")\np nm(k)\np nm(k.v = nilf)\n"
H["as_kwarg"] = "def kwf(a: 1, b: 2)\n  p a\n  p b\nend\nk = K.new\nkwf(b: (k.v = nilf))\n"
H["as_splat"] = "def spl(*a)\n  p a\nend\nk = K.new\nspl(1, (k.v = nilf), 2)\n"
H["as_blockarg"] = "k = K.new\n[1].each { |i| p(k.v = nilf) }\nr = [1, 2].select { |i| k.v = nilf }\np r\nr2 = [1, 2].reject { |i| k.v = bump }\np r2\np [3, 4].map { |i| k.w = nilf }.compact\np([1, 2].all? { |i| k.v = nilf })\np([1, 2].find { |i| k.v = nilf })\np [1, 2].count { |i| k.v = nilf }\n"
H["as_each_with"] = "k = K.new\nr = [1, 2].each_with_object([]) { |i, acc| acc << (k.v = nilf) }\np r\np [1, 2].inject(0) { |s, i| (k.v = nilf); s + i }\n"
H["gc_fresh_val_obj"] = "class Big\n  def initialize(i)\n    @s = \"big\" * (i + 1)\n  end\nend\ndef mknil(b)\n  nil\nend\nt = 0\n300.times do |i|\n  k = K.new(\"k\#{i}\")\n  k.v = mknil(Big.new(i))\n  t += 1 if k.v.nil? && k.name == \"k\#{i}\"\nend\np t\n"
H["gc_fresh_recv_chain"] = "class Hd\n  def initialize(i)\n    @o = K.new(\"o\#{i}\")\n  end\n  def o = @o\nend\ndef mknil(s)\n  nil\nend\nt = 0\n300.times do |i|\n  h = Hd.new(i)\n  r = (h.o.v = mknil(\"s\#{i}\" * 3))\n  t += 1 if r.nil? && h.o.v.nil? && h.o.name == \"o\#{i}\"\nend\np t\n"
H["gc_fresh_new_recv"] = "class Lg\n  def initialize(i)\n    @n = \"n\#{i}\"\n  end\n  def v=(x)\n    $acc << @n\n    @v = x\n  end\nend\n$acc = []\ndef mknil(s)\n  $tmp = s + \"?\"\n  nil\nend\n200.times do |i|\n  Lg.new(i).v = mknil(\"s\#{i}\" * 3)\nend\np $acc.size\np $acc.last\np $acc.join.length\n"
H["gc_fresh_strslot"] = "class Sv\n  def v=(x)\n    @v = x\n  end\n  def v = @v\nend\ndef mknil(s)\n  $tmp = s + \"?\"\n  nil\nend\nt = 0\n200.times do |i|\n  o = Sv.new\n  o.v = \"str\#{i}\"\n  r = (o.v = mknil(\"s\#{i}\"))\n  t += 1 if r.nil? && o.v.nil?\n  o.v = \"again\#{i}\"\n  t += o.v.length\nend\np t\n"
H.each { |n, body| File.write("/home/claude/r8/p220/g_hand/#{n}.rb", PRE + body) }
puts H.size
