PRE = <<~'RB'
  def nilf
    puts "nilf"
    nil
  end
  class K
    def v=(x)
      @v = x
      42
    end
    def v = @v
  end
  a = K.new
RB
L = {
  "procarr" => ["procs = [-> { nil }, -> { 5 }]", "procs[1].call"],
  "procarr2" => ["procs = [-> { nil }]\nprocs << -> { 5 }", "procs.last.call"],
  "prochash" => ["ph = {a: -> { nil }, b: -> { \"s\" }}", "ph[:b].call"],
  "procvar" => ["pr = -> { nil }\npr = -> { 6 } if a", "pr.call"],
  "procret" => ["def mkp(f) = f ? -> { 7 } : -> { nil }", "mkp(true).call"],
  "procparam" => ["def callit(pr) = pr.call\ncallit(-> { nil })", "callit(-> { 8 })"],
  "yieldtwo" => ["def yv\n  yield\nend\nyv { nil }", "yv { 9 }"],
  "yieldtwo2" => ["def yv\n  yield\nend\nx9 = yv { 9 }", "yv { nilf }"],
  "blkpass" => ["def yv(&b) = b.call\nyv { nil }", "yv { 10 }"],
  "ivget" => ["class Q\n  def z = @z\nend\nq = Q.new\nq.instance_variable_set(:@z, 7)", "q.z"],
  "ivget2" => ["class Q\n  def initialize\n    @z = nil\n  end\n  def z = @z\nend\nq = Q.new\nq.instance_variable_set(:@z, 7)", "q.z"],
  "sendn" => ["def five = 5\nnm = :five", "send(nm)"],
  "psend" => ["class Q\n  def five = 5\n  def none = nil\nend\nq = Q.new\nnm = [:none, :five][1]", "q.public_send(nm)"],
  "defm" => ["class Q\n  define_method(:dm) { 11 }\nend\nq = Q.new", "q.dm"],
  "mmiss" => ["class Q\n  def method_missing(n, *args) = 12\n  def respond_to_missing?(*) = true\nend\nq = Q.new", "q.anything"],
  "redef" => ["def rd = nil\ndef rd = 13", "rd"],
  "redef2" => ["def rd = nil\nx1 = rd\nclass Object\n  def rd = 13\nend", "rd"],
  "eachbreak" => ["", "[1, 2].each { |i| break if i > 1 }"],
  "loopbreak" => ["", "loop { break }"],
  "loopbreakv" => ["", "loop { break 14 }"],
  "whilebreak" => ["i = 0", "(while true; i += 1; break if i > 2; end)"],
  "whilebreakv" => ["i = 0", "(while true; i += 1; break 15 if i > 2; end)"],
  "catchv" => ["", "catch(:t) { throw :t, 16 }"],
  "catchn" => ["", "catch(:t) { throw :t }"],
  "catchnil" => ["", "catch(:t) { nil }"],
  "nonlocal" => ["def fnd(arr)\n  arr.each { |x| return x if x > 1 }\n  nil\nend", "fnd([1, 2, 3])"],
  "nonlocal2" => ["def fnd(arr)\n  arr.each { |x| return \"s\#{x}\" if x > 1 }\n  nil\nend", "fnd([1, 2, 3])"],
  "rescueval" => ["def rv\n  raise \"x\"\n  nil\nrescue\n  17\nend", "rv"],
  "ensureval" => ["def ev\n  return 18\nensure\n  nil\nend", "ev"],
  "rescret" => ["def rr\n  nil\nrescue\n  nil\nelse\n  19\nend", "rr"],
  "condmeth" => ["def cm(x)\n  if x > 1\n    20\n  end\nend", "cm(2)"],
  "casemeth" => ["def cs(x)\n  case x\n  when 1 then nil\n  when 2 then 21\n  end\nend", "cs(2)"],
  "andmeth" => ["def am(x) = x && nil\ndef bm(x) = nil || x", "bm(22)"],
  "tapv" => ["", "nil.tap { }.then { 23 }"],
  "thenv" => ["", "nilf.then { |x| 24 }"],
  "orelse" => ["", "(nilf || 25)"],
  "itself" => ["", "nil.itself.to_a.push(26).last"],
  "struct" => ["S = Struct.new(:m)\ns = S.new\ns.m = 27", "s.m"],
  "structnil" => ["S = Struct.new(:m)\ns = S.new", "s.m"],
  "hashdef" => ["hd = Hash.new { |h, k| 28 }", "hd[:zz]"],
  "hashnil" => ["hn = {a: nil}\nhn[:a] = 29", "hn[:a]"],
  "arrnil" => ["an = [nil, nil]\nan[0] = 30", "an[0]"],
  "arrnil2" => ["an = [nil, nil]\nan << 31", "an.last"],
  "arrnil3" => ["an = [nil]", "an.first"],
  "arrnil4" => ["an = Array.new(2)\nan[1] = 32", "an[1]"],
  "gvar2" => ["$gq = nil\ndef setg = $gq = 33\nsetg", "($gq)"],
  "const2" => ["NC = nil\nNC2 = NC || 34", "(NC2)"],
  "ivar_top" => ["@ti = nil\n@ti = 35 if a", "(@ti)"],
  "localblk" => ["t = nil\n[1].each { t = 36 }", "(t)"],
  "locallam" => ["t = nil\nl = -> { t = 37 }\nl.call", "(t)"],
  "localeval" => ["t = nil\nbinding.local_variable_set(:t, 38)", "(t)"],
  "dflt" => ["def df(q = nil) = (q)\ndf", "df(39)"],
  "kwdflt" => ["def kd(q: nil) = (q)\nkd", "kd(q: 40)"],
  "optblock" => ["def ob\n  yield if block_given?\nend\nob", "ob { 41 }"],
  "super_m" => ["class P1\n  def m = 42\nend\nclass P2 < P1\n  def m\n    super\n    nil\n  end\nend\nclass P3 < P2\n  def m = 43\nend\ndef pk(f) = f ? P3.new : P2.new\npo = pk(true)", "po.m"],
  "over_m" => ["class P1\n  def m = nil\nend\nclass P2 < P1\n  def m = 44\nend\nxs = [P1.new, P2.new]", "xs[1].m"],
  "over_m2" => ["class P1\n  def m = nil\nend\nclass P2 < P1\n  def m = 44\nend\ndef mk1(f) = f ? P2.new : P1.new\nxo = mk1(true)", "xo.m"],
  "mod_m" => ["module Mx\n  def m = nil\nend\nclass P1\n  include Mx\nend\nclass P2\n  include Mx\n  def m = 45\nend\nxo = P2.new", "xo.m"],
  "prepend_m" => ["module Mx\n  def m = 46\nend\nclass P1\n  def m = nil\n  prepend Mx\nend\nxo = P1.new", "xo.m"],
  "sing_m" => ["class P1\n  def m = nil\nend\nxo = P1.new\ndef xo.m = 47", "xo.m"],
  "reopen_m" => ["class P1\n  def m = nil\nend\nxo = P1.new\nclass P1\n  def m = 48\nend", "xo.m"],
  "alias_m" => ["class P1\n  def m = nil\n  def n = 49\n  alias m n\nend\nxo = P1.new", "xo.m"],
  "undef_m" => ["class P0\n  def m = 50\nend\nclass P1 < P0\n  def m = nil\n  remove_method :m\nend\nxo = P1.new", "xo.m"],
  "refine" => ["class P1\n  def m = nil\nend\nxo = P1.new", "xo.m.to_a.size"],
  "raise_only" => ["def boom\n  raise \"boom\"\nend", "boom"],
  "exit_v" => ["", "exit"],
  "abort_v" => ["", "(puts \"bye\"; exit(0))"],
  "fiber" => ["fb = Fiber.new { Fiber.yield 51; nil }", "fb.resume"],
  "enumnext" => ["en = [nil, 52].each\nen.next", "en.next"],
  "symproc" => ["", "[53].map(&:itself).first"],
  "methobj" => ["def five = 54\nm = method(:five)", "m.call"],
  "ternlie" => ["def tl(x) = x ? nil : nil", "tl(1)"],
  "nilsafe" => ["class P1\n  def m = 55\nend\nxo = P1.new\nxn = nil\nxn = xo if a", "xn&.m"],
  "argnil" => ["def idn(x) = x\nidn(nil)", "idn(56)"],
  "argnil2" => ["def idn(x) = x\nx1 = idn(57)", "idn(nil)"],
  "argnil3" => ["def idn(x) = (x)", "idn(nil)"],
  "blkargnil" => ["", "[nil].map { |x| x }.first"],
  "eachnil" => ["", "[nil, 58].last"],
  "comparable" => ["", "(1 <=> \"a\")"],
  "nonzero" => ["", "0.nonzero?"],
  "nonzero2" => ["", "5.nonzero?"],
  "strslice" => ["", "\"abc\"[9]"],
  "matchnil" => ["", "(\"abc\" =~ /z/)"],
  "matchv" => ["", "(\"abc\" =~ /b/)"],
  "objeq" => ["", "(a.frozen? ? nil : 59)"],
  "integerq" => ["", "Integer(\"60\") rescue nil"],
  "unlessv" => ["", "(61 unless nil)"],
  "puts_ret" => ["", "$stdout.puts(\"q\")"],
  "print_ret" => ["", "$stdout.print(\"q\\n\")"],
  "write_ret" => ["", "$stdout.write(\"q\\n\")"],
  "flush_ret" => ["", "$stdout.flush.nil? ? 62 : nil"],
  "srand" => ["", "(srand(1); nil)"],
  "sleep" => ["", "sleep(0)"],
  "gc" => ["", "GC.start"],
  "arr_clear" => ["", "[1].clear.first"],
  "sort_bang" => ["", "[2, 1].uniq!"],
  "sort_bang2" => ["", "[1, 1].uniq!"],
  "str_bang" => ["", "(+\"abc\").upcase!"],
  "str_bang2" => ["", "(+\"ABC\").upcase!"],
  "squeeze" => ["", "(+\"abc\").squeeze!"],
  "chomp" => ["", "(+\"abc\").chomp!"],
  "compact" => ["", "[1, 2].compact!"],
  "flatten" => ["", "[1, 2].flatten!"],
  "reject" => ["", "[1, 2].reject! { |x| x > 5 }"],
  "select" => ["", "[1, 2].select! { |x| x > 0 }"],
  "hreject" => ["", "{a: 1}.reject! { |k, v| v > 5 }"],
  "hdelete" => ["", "{a: 1}.delete(:b)"],
  "adelete" => ["", "[1, 2].delete(3)"],
  "slice" => ["", "[1, 2].slice!(5)"],
  "ashift" => ["", "[].shift"],
  "apop" => ["", "[].pop"],
  "amax" => ["", "[].max"],
  "asum" => ["", "[].first"],
  "afind" => ["", "[1, 2].find { |x| x > 5 }"],
  "aindex" => ["", "[1, 2].index(7)"],
  "sindex" => ["", "\"abc\".index(\"z\")"],
  "hfetchn" => ["", "{a: nil}.fetch(:a)"],
  "hdig" => ["", "{a: {b: nil}}.dig(:a, :b)"],
  "adig" => ["", "[[nil]].dig(0, 0)"],
  "times_ret" => ["", "(3.times { })"],
  "each_ret" => ["", "([1].each { })"],
  "upto" => ["", "1.step(3, 5) { }"],
  "ifnil" => ["", "(if a.nil? then 63 end)"],
  "unlessnil" => ["", "(unless a.nil? then 64 end)"],
  "whileret" => ["", "(until true do end)"],
  "defret" => ["", "(def zz9 = 1)"],
  "classret" => ["", "(class Zz; end)"],
  "classret2" => ["", "(class Zz; 65; end)"],
  "modret" => ["", "(module Zm; nil; end)"],
  "beginend" => ["", "(begin; end)"],
  "emptyparen" => ["", "()"],
  "notnil" => ["", "(not nil)"],
  "defined" => ["", "defined?(zzz)"],
  "defined2" => ["", "defined?(a)"],
  "flipflop" => ["", "(nil if (a.v == 1)..(a.v == 2))"],
  "lambda_ret" => ["l = lambda { return nil }", "l.call"],
  "lambda_next" => ["l = lambda { next }", "l.call"],
  "proc_next" => ["pr = proc { next }", "pr.call"],
  "proc_new" => ["pr = Proc.new { |x| x }", "pr.call(nil)"],
  "proc_new2" => ["pr = Proc.new { |x| x }\nx1 = pr.call(nil)", "pr.call(66)"],
  "curry" => ["l = ->(x, y) { nil }", "l.curry[1][2]"],
  "yield_self" => ["", "67.then { nil }"],
  "instance_eval" => ["", "a.instance_eval { nil }"],
  "instance_exec" => ["", "a.instance_exec(68) { |x| x }"],
  "obj_method" => ["", "a.v"],
  "obj_method2" => ["a.v = 69", "a.v"],
}
L.each { |n, (pre, ex)| File.write("/home/claude/r8/p220/g_lie/#{n}.rb", PRE + (pre.empty? ? "" : pre + "\n") + "r = (a.v = #{ex})\np r\np a.v\n") }
puts L.size
