K = 'puts(case %s when nil then "%s nil" when false then "%s false" when true then "%s true" else "%s other" end)'
def k(e, tag) = K % [e, tag, tag, tag, tag]
progs = []
progs << ["bs = [3 > 5]", "a, b = bs", k("b", "masgn")]
progs << ["a, b = [3 > 5]", k("b", "masgn-lit")]
progs << ["a, b = 3 > 5", k("b", "masgn-scalar")]
progs << ["a, (b, c) = true, [false]", k("c", "masgn-nest")]
progs << ["bs = [true, false, true]", "bs.each_slice(2) { |a, b| #{k('b', 'slice')} }"]
progs << ["rows = [[true, false], [true]]", "rows.each { |a, b| #{k('b', 'rows')} }"]
progs << ["def y2 = yield(3 > 5)", "y2 { |a, b| #{k('b', 'yield-short')} }"]
progs << ["bs = [true, false]", "bs.zip([true]) { |a, b| #{k('b', 'zip')} }"]
progs << ["bs = [true, false]", "bs.zip([true]).each { |a, b| #{k('b', 'zip-each')} }"]
progs << ["pr = proc { |a, b| #{k('b', 'proc-short')} }", "pr.call(3 > 5)"]
progs << ["la = ->(a, b = nil) { #{k('b', 'lambda-dflt')} }", "la.call(3 > 5)", "la.call(true, false)"]
progs << ["def opt(a, b = nil) = #{k('b', 'opt')[5..-2]}", "puts opt(1)", "puts opt(1, 3 > 5)"]
progs << ["for fb in [false]; end", k("fb", "for-after")]
progs << ["[1].each { |i; bl| #{k('bl', 'blocklocal')}; bl = i > 5 }"]
progs << ["2.times { |i| bw = i > 5 if i > 0; #{k('bw', 'block-unset')} }"]
progs << ["case [true] in [x, *r] then nil end", k("r.first", "pat-rest")]
progs << ["h = { a: true }", "case h in { a: pa } then nil end", k("pa", "pat")]
progs << ["ok = (begin; Integer('z') > 1; rescue; end)", k("ok", "begin-rescue-val")]
progs << ["ok2 = (Integer('z') > 1 rescue nil)", k("ok2", "rescue-mod")]
progs << ["def tk(a = (3 > 5), b = a) = #{k('b', 'dflt-chain')[5..-2]}", "puts tk"]
progs << ["$gb = 3 > 5 if ARGV.size > 5", k("$gb", "gvar-unset")]
progs << ["CB = (3 > 5 if ARGV.size > 5)", k("CB", "const")]
progs << ["x = nil", "x ||= 3 > 5", k("x", "or-write")]
progs << ["ow ||= 3 > 5", k("ow", "or-write-fresh")]
progs << ["aw &&= 3 > 5", k("aw", "and-write-fresh")]
progs << ["sw = (sw2 = 3 > 5 if ARGV.size > 5)", k("sw", "if-mod-val"), k("sw2", "if-mod-inner")]
progs << ["t = [1, 2].map { |e| e > 5 }.find { |e| e }", k("t", "find-miss")]
progs << ["t2 = [false].compact.first", k("t2", "first-empty")]
progs << ["wl = nil", "while wl.nil?; wl = 3 > 5; end", k("wl", "while-nil")]
progs << ["i = 0", "until i > 0; ul = i > 5; i += 1; end", k("ul", "until-set")]
progs << ["i = 9", "until i > 0; ul2 = i > 5; i += 1; end", k("ul2", "until-unset")]
progs.each_with_index { |ls, i| File.write("p8_%02d.rb" % i, ls.join("\n") + "\n") }
