"\xFF\x00a\xFF\x00a" String
#<Encoding:ASCII-8BIT> Encoding
6 Integer
false FalseClass
"h\u00E9h\u00E9" String
#<Encoding:UTF-8> Encoding
6 Integer
false FalseClass
"abab" String
#<Encoding:UTF-8> Encoding
4 Integer
false FalseClass
"symsym" String
#<Encoding:US-ASCII> Encoding
6 Integer
false FalseClass
"77" String
#<Encoding:US-ASCII> Encoding
2 Integer
false FalseClass
